[package]
name = "derive_stringset"
version = "0.1.0"
authors = ["James Irwin <irwineffect@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = {version="1.0.58", features=["extra-traits"]}
quote = "1.0.8"
proc-macro2 = "1.0.24"